package com.cgx.dto;
// Generated 2017-7-12 11:18:15 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Meeting generated by hbm2java
 */
@Entity
@Table(name = "meeting", catalog = "test")
public class Meeting implements java.io.Serializable {

	private Integer id;
	private String sender;
	private String starttime;
	private String endtime;
	private String address;
	private String title;
	private String content;

	public Meeting() {
	}

	public Meeting(String sender) {
		this.sender = sender;
	}

	public Meeting(String sender, String starttime, String endtime, String address, String title, String content) {
		this.sender = sender;
		this.starttime = starttime;
		this.endtime = endtime;
		this.address = address;
		this.title = title;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sender", nullable = false, length = 50)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "starttime", length = 20)
	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	@Column(name = "endtime", length = 20)
	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
